version: '3'
services:
  # Create frontend container
  frontend: # Name of our service

    environment:
      - API_HOST="http://localhost:3001"
    build: ./client # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    #links:
     # - backend
  # Create backend container
  backend:
    # Create backend container
    environment:
      - API_HOST="http://localhost:3000"
    build: ./server
    ports:
      - "8080:8080"
    container_name: backend-docker
    restart: always
    links:
      - my-db
  # Create database container
  my-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'chat_test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'epy'
      # You can use whatever password you like
      MYSQL_PASSWORD: '01234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '01234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "5432:5432"
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql/
  # Names our volume
volumes:
  my-db:
